### ISSUE TITLE
name 'namespace' is not defined +   Invalid <param> tag

### ISSUE THREAD

**Issue by johnwaneboy** [uzh-rpg/rpg_quadrotor_control#111]
There is a strange issue.  I have install and run the program successfully, and no adjustments were made. When I ran again, the following problems occurred.  I reinstall and run, the same problem is the same.   

name 'namespace' is not defined 
when evaluating expression 'namespace'
when processing file: /home/wane/catkin_ws/src/rotors_simulator/rotors_description/urdf/component_snippets.xacro
included from: /home/wane/catkin_ws/src/rotors_simulator/rotors_description/urdf/hummingbird_base.xacro
included from: /home/wane/catkin_ws/src/rotors_simulator/rotors_description/urdf/mav_generic_odometry_sensor.gazebo
RLException: while processing /home/wane/catkin_ws/src/rpg_quadrotor_control/simulation/rpg_rotors_interface/launch/basics/base_quad_simulation.launch:
while processing /home/wane/catkin_ws/src/rotors_simulator/rotors_gazebo/launch/spawn_mav.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/home/wane/catkin_ws/src/rotors_simulator/rotors_description/urdf/mav_generic_odometry_sensor.gazebo', 'enable_logging:=false', 'enable_ground_truth:=true', 'enable_mavlink_interface:=false', 'log_file:=hummingbird', 'wait_to_record_bag:=false', 'mav_name:=hummingbird', 'namespace:=hummingbird']] returned with code [2]. 

Param xml is <param command="     $(find xacro)/xacro '$(arg model)'     enable_logging:=$(arg enable_logging)     enable_ground_truth:=$(arg enable_ground_truth)     enable_mavlink_interface:=$(arg enable_mavlink_interface)     log_file:=$(arg log_file)     wait_to_record_bag:=$(arg wait_to_record_bag)     mav_name:=$(arg mav_name)     namespace:=$(arg namespace)" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by CK1201** [comment]
https://github.com/ethz-asl/rotors_simulator/issues/695
