### ISSUE TITLE
Drone does not take off

### ISSUE THREAD

**Issue by souravsanyal06** [uzh-rpg/rpg_quadrotor_control#113]
When I click on the arm bridge and click on Start, nothing happens

I get the following prompt:

[ERROR] [1656103595.738987768, 14.710000000]: [/hummingbird/autopilot] No state estimate available, will not start

**Comment by souravsanyal06** [comment]
.

**Comment by Mealoore** [comment]
I met it ,too, do you solve the problem?

**Comment by xiaoshengjianan** [comment]
How did you solve it?
