### ISSUE TITLE
Wrong/unclear braking procedure?

### ISSUE THREAD

**Issue by foehnph** [uzh-rpg/rpg_quadrotor_control#55]
https://github.com/uzh-rpg/rpg_quadrotor_control/blob/522f549d9f716de04d4fc3bb22056a4a0a60532b/control/autopilot/src/autopilot.cpp#L984

how is this braking the quad?
doesn't it just continue with the estimated velocity?

**Comment by kohlerj** [comment]
I allowed myself to intervene and explained it to mr. foehn ;)
