### ISSUE TITLE
Trapezoidal velocity profile for start maneuver

### ISSUE THREAD

**Issue by mfaessle** [uzh-rpg/rpg_quadrotor_control#64]
The MPC controller needs a non zero acceleration to start nicely but currently it is implemented in a hacky way. Ideally the start procedure would be a proper trapeziodal velocity profile.

**Comment by foehnph** [comment]
addressed in #60

**Comment by mfaessle** [comment]
The position is not the integral of the velocity yet ;) But seriously, this can be addressed if ever someone cares. Then we could also break the velocity down towards the start height.
