### ISSUE TITLE
I can't find the firmware  Betaflight / VGOODDHF4 3.1.7

### ISSUE THREAD

**Issue by neoneo1716** [uzh-rpg/rpg_quadrotor_control#90]
i want to know where can it download? I find everywhere but i can't find it . it seem to too old to find in the Betaflight configure.thanks

**Comment by mfaessle** [comment]
You can find it on their release page: https://github.com/betaflight/betaflight/releases?after=1.7.0-RC1
This version is very old by now. Newer versions with corresponding parameter adaptations that we propose here should work as well but there is no guarantee. We might update them at some point as it was attempted in #82 but never merged.
